import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import 'remixicon/fonts/remixicon.css'
import './main.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Irregular verbs app',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>): JSX.Element {
	return (
		<html lang="en" className="bg-slate-900 text-slate-300 antialiased">
			<body className={`${inter.className}`}>{children}</body>
		</html>
	)
}
